services:
  mysql:
    image: mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - beam_db_data:/var/lib/mysql
  test-db:
    image: mysql
    env_file: .env.test
    ports:
      - 3308:3308
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  nestjs:
    build: .
    container_name: nestjs
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - ${PORT}:8080
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  beam_db_data: