services:
  mysql:
    image: mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - /var/lib/mysql
  test-db:
    image: mysql
    ports:
      - 3308:3308
    restart: always
    environment:
      MYSQL_DATABASE: myapp_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
  nestjs:
    build: .
    container_name: nestjs
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - ${PORT}:8080
    volumes:
      - .:/app
    command: npm run start:dev



