services:
  mysql:
    image: mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql-data:/var/lib/mysql
  nestjs:
    build: .
    container_name: nestjs
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - ${PORT}:3001
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  mysql-data:


